version: "3"

networks:
	inception:

volumes:
	v_wordpress:

	v_database:

services:
  nginx:
    image: nginx:inc
    restart: always
    ports:
        - "443:443"
    build:
      context: srcs/services/NGINX
      dockerfile: Dockerfile
    networks:
      - inception
    env_file: .env

  wordpress:
    depends_on:
      - mariadb
		container_name:
		hostname:
		build:
		restart: "always"
		volumes:
		-
		networks:
		  - inception
		  
	mariadb:
		container_name:
		hostname:
		build:
		restart: "always"
		ports:
		-
		volumes:
		-
		-
		networks:
		  - inception